server:
  port: 8888

# mybatis配置
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    # 控制台打印mybatis操作日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  # 数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #开发
    #url: jdbc:mysql://10.249.47.167:3306/fmsmysqldev02?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    #username: fmsmysqldev
    #password: AH9CZJ4nTwHsXE_4ay
    #测试
    url: jdbc:mysql://10.249.47.156:3306/fmsmysqlqas02?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: fmsmysqlqas
    password: 9KdMhE9N98SdK4tFgB

  # redis
  redis:
    # Redis数据库索引(默认为0)
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456
    # 连接超时时间（毫秒）
    timeout: 1000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 5000
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0

#pagehelper分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true


